(function () {
  window.GR_EVENTS = {
    events: [
      {
        slug: 'taipei-101-seminar',
        status: 'upcoming',
        featured: true,
        category: 'seminar',
        categoryLabel: '說明會系列',
        date: '2026-07-25',
        dateLabel: '2026/7/25',
        dateDisplay: '2026 / 07 / 25 (六) 下午 2:00 起',
        title: '澳洲置產說明會.台北文華東方',
        summary:
          '於文華東方舉辦，解析澳洲樓市趨勢、精選建案與海外買家合規要點，並提供一對一諮詢。',
        image: 'assets/images/gallery/event-mandarin-0725-poster.jpg',
        imageAlt: '623 Collins 澳洲資產配置紅酒品鑑會海報 · 台北文華東方',
        heroImage: 'assets/images/gallery/event-still-05.jpg',
        posterImage: 'assets/images/gallery/event-mandarin-0725-poster.jpg',
        location: '台北市松山區敦化北路 158 號 · 台北文華東方',
        typeLabel: '置產說明會',
        ctaLabel: '預約下一場',
        ctaUrl: 'index.html#consult',
        introLead: '環球置業 · 台北文華東方 · 澳洲置產說明會',
        body: [
          '環球置業定期於台北文華東方舉辦澳洲置產說明會，為台灣高資產客戶解析雪梨、墨爾本核心商圈最新樓市動態，並分享海外買家須知的 FIRB 申請、稅務與交割流程要點。',
          '現場由資深置業顧問介紹環球置業嚴選建案，包含期房與現房配置方案，並可預約一對一諮詢，依您的預算、用途與持有策略提供參考方向。',
          '說明會採小班制進行，名額有限，歡迎事先填寫諮詢表單或來電預約，以便為您保留席位並準備相關資料。',
        ],
        details: [
          { label: '活動形式', value: '現場說明會 · 一對一諮詢' },
          { label: '適合對象', value: '計畫布局澳洲置產的台灣投資者與家庭' },
          { label: '報名方式', value: '官網諮詢表單或 Email 預約' },
        ],
      },
      {
        slug: 'taipei-101-aura-wine-tasting',
        status: 'upcoming',
        featured: true,
        category: 'themed',
        categoryLabel: '主題活動',
        date: '2026-07-26',
        dateLabel: '2026/7/26',
        dateDisplay: '2026 / 07 / 26 (日) 10:30 – 16:30',
        title: '澳洲資產配置紅酒品鑑會 · AURA 專場 · 台北 101',
        summary:
          '於台北 101 88 樓舉辦 AURA 專場，結合澳洲資產配置與紅酒品鑑，探討陪讀定居、退休養生、財產配置與穩定收租等置產方向。',
        image: 'assets/images/gallery/event-101-aura-0726-poster.jpg',
        imageAlt: '台北 101 AURA 澳洲資產配置紅酒品鑑會海報',
        heroImage: 'assets/images/gallery/event-still-03.jpg',
        posterImage: 'assets/images/gallery/event-101-aura-0726-poster.jpg',
        location: '台北市信義區信義路五段 7 號 · 台北 101 88 樓',
        typeLabel: '主題品鑑會',
        ctaLabel: '預約席位',
        ctaUrl: 'index.html#consult',
        introLead: '環球置業 · 台北 101 · AURA 澳洲資產配置紅酒品鑑會',
        body: [
          '環球置業於台北 101 88 樓舉辦台北場限定 AURA 專場，以紅酒品鑑搭配澳洲資產配置分享，為貴賓介紹墨爾本南岸河景旗艦建案 AURA 的區位優勢與置產策略。',
          '活動聚焦陪讀定居、退休養生、財產配置與穩定收租等多元需求，由置業顧問現場解析海外買家合規要點，並提供一對一諮詢。現場限定釋出專屬優惠與席位名額。',
          '席位有限，敬邀預約出席。歡迎透過官網諮詢表單或 Email 留下聯絡方式，以便為您保留名額。',
        ],
        details: [
          { label: '活動形式', value: '紅酒品鑑 · AURA 專場分享 · 一對一諮詢' },
          { label: '適合對象', value: '關注墨爾本南岸置產、偏好小型品鑑活動的貴賓' },
          { label: '報名方式', value: '官網諮詢表單或 Email 預約' },
        ],
      },
    ],
  };
})();
