/** 設計預覽站共用頁面清單 */
window.DESIGN_PAGES = [
  {
    id: '01-index',
    num: '01',
    title: '首頁',
    live: '../index.html',
    png: 'desktop/01-index.png',
    pageId: 'home',
  },
  {
    id: '02-properties',
    num: '02',
    title: '精選建案',
    live: '../properties.html',
    png: 'desktop/02-properties.png',
    pageId: 'properties',
  },
  {
    id: '03-leasing',
    num: '03',
    title: '租賃管理',
    live: '../leasing.html',
    png: 'desktop/03-leasing.png',
    pageId: 'leasing',
  },
  {
    id: '04-events',
    num: '04',
    title: '活動預告',
    live: '../events.html',
    png: 'desktop/04-events.png',
    pageId: 'events',
  },
  {
    id: '05-classroom',
    num: '05',
    title: '澳洲不動產小課堂',
    live: '../classroom.html',
    png: 'desktop/05-classroom.png',
    pageId: 'classroom',
  },
  {
    id: '06-about',
    num: '06',
    title: '關於環球置業',
    subtitle: '關於我們 · 子分頁',
    live: '../about.html',
    png: 'desktop/06-about.png',
    pageId: 'about',
  },
  {
    id: '07-group',
    num: '07',
    title: '澳華國際集團',
    subtitle: '關於我們 · 子分頁',
    live: '../group.html',
    png: 'desktop/07-group.png',
    pageId: 'group',
  },
];
