/** 設計預覽站共用頁面清單（命名：网站-01 … 网站-08） */
window.DESIGN_PAGES = [
  {
    id: '网站-01',
    num: '01',
    title: '首頁',
    live: '../index.html',
    png: 'desktop/网站-01.png',
    pageId: 'home',
  },
  {
    id: '网站-02',
    num: '02',
    title: '精選建案',
    live: '../properties.html',
    png: 'desktop/网站-02.png',
    pageId: 'properties',
  },
  {
    id: '网站-03',
    num: '03',
    title: '租賃管理',
    live: '../leasing.html',
    png: 'desktop/网站-03.png',
    pageId: 'leasing',
  },
  {
    id: '网站-04',
    num: '04',
    title: '活動預告',
    live: '../events.html',
    png: 'desktop/网站-04.png',
    pageId: 'events',
  },
  {
    id: '网站-05',
    num: '05',
    title: '澳洲不動產小課堂',
    live: '../classroom.html',
    png: 'desktop/网站-05.png',
    pageId: 'classroom',
  },
  {
    id: '网站-06',
    num: '06',
    title: '關於環球置業',
    subtitle: '關於我們 · 子分頁',
    live: '../about.html',
    png: 'desktop/网站-06.png',
    pageId: 'about',
  },
  {
    id: '网站-07',
    num: '07',
    title: '澳華國際集團',
    subtitle: '關於我們 · 子分頁',
    live: '../group.html',
    png: 'desktop/网站-07.png',
    pageId: 'group',
  },
  {
    id: '网站-08',
    num: '08',
    title: '隱私權政策',
    live: '../privacy.html',
    png: 'desktop/网站-08.png',
    pageId: 'privacy',
  },
];
